name: Run init_vm Script

on:
  workflow_dispatch: # Manual trigger

jobs:
  run-init-vm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/gcloud-key.json
      run: |
        echo "${{ secrets.GCLOUD_SERVICE_KEY }}" > $GOOGLE_APPLICATION_CREDENTIALS
        gcloud auth activate-service-account nvim-service-account@eran-sandbox.iam.gserviceaccount.com --key-file=$GOOGLE_APPLICATION_CREDENTIALS
        gcloud config set project YOUR_PROJECT_ID

    - name: Run init_vm.sh
      run: |
        chmod +x ./init_vm.sh
        ./dockers/my-nvim/docker_vm_create_command.sh
